#!/bin/bash
set -o nounset

# Source YunoHost helpers
source _future.sh
source /usr/share/yunohost/helpers

# Retrieve app settings
readonly app=$YNH_APP_INSTANCE_NAME
readonly domain=$(ynh_app_setting_get "$app" domain)
readonly app_system_name=$(ynh_app_setting_get "$app" system_name)
readonly final_path=/var/www/$app_system_name
readonly db_type=$(ynh_app_setting_get "$app" db_type)


function main()
{
    clear_db

    # Remove dependencies
    ynh_remove_app_dependencies

    clear_configuration
    remove_service

    # Remove sources
    ynh_secure_remove --file=$final_path

    # Delete system user
    ynh_system_user_delete --username=$app_system_name

    # Reload nginx service
    service nginx reload
}

function clear_db()
{
    case $db_type in
        "postgresql")
            # Remove postgresql table
            ynh_psql_drop_db $app_system_name
            ynh_psql_drop_user $app_system_name
            ;;
        "sqlite")
            # Remove sqlite table
            ynh_sqlite_drop_db $app_system_name
            ;;
        *)
            ynh_print_err --message="Unknown database type, proceeding to app removing anyway.."
            ;;
    esac
}

function clear_configuration()
{
    # Remove nginx configuration file
    ynh_secure_remove --file=/etc/nginx/conf.d/$domain.d/$app_system_name.conf
}

function remove_service()
{
    # Remove services
    service $app_system_name stop
    killall $app_system_name
    yunohost service remove $app_system_name
    ynh_secure_remove --file=/etc/systemd/system/$app_system_name.service
    systemctl daemon-reload
}

main
